### ISSUE TITLE
StringIndexOutOfBoundException when ResultsActivity calls backend

### ISSUE THREAD

**Issue by CoolCapri** [alaurenz/metrobike#144]
The app crashes when you are setting both addresses as current location.

Here is basically how current location in SearchActivity works:
1. You can press the blue buttons on the left of the address boxes to use current location instead of a specific position.
2. SearchActivity will call Google Play Location Services to find current latitude and longitude, both are double types.
3. SearchActivity converts the lat and lang to String (in "lat, long" format), call doRequest(), and then pass the result to ResultActivity if request is successful.

Now the problem is, when you are setting _both_ addresses as current location, SearchActivity successfully gets the result from backend, and send it to ResultsActivity. Now the app crashes due to a StringIndexOutOfBoundException when ResultsActivity calls backend to get secondsToHumanReadableDuration(), as follows:

05-23 23:35:08.831: E/AndroidRuntime(30761): FATAL EXCEPTION: main
05-23 23:35:08.831: E/AndroidRuntime(30761): java.lang.RuntimeException: Unable to resume activity {com.HuskySoft.metrobike/com.HuskySoft.metrobike.ui.ResultsActivity}: java.lang.StringIndexOutOfBoundsException: length=0; regionStart=0; regionLength=-2
05-23 23:35:08.831: E/AndroidRuntime(30761):    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2742)
05-23 23:35:08.831: E/AndroidRuntime(30761):    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2771)
05-23 23:35:08.831: E/AndroidRuntime(30761):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2235)
05-23 23:35:08.831: E/AndroidRuntime(30761):    at android.app.ActivityThread.access$600(ActivityThread.java:141)
05-23 23:35:08.831: E/AndroidRuntime(30761):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
05-23 23:35:08.831: E/AndroidRuntime(30761):    at android.os.Handler.dispatchMessage(Handler.java:99)
05-23 23:35:08.831: E/AndroidRuntime(30761):    at android.os.Looper.loop(Looper.java:137)
05-23 23:35:08.831: E/AndroidRuntime(30761):    at android.app.ActivityThread.main(ActivityThread.java:5041)
05-23 23:35:08.831: E/AndroidRuntime(30761):    at java.lang.reflect.Method.invokeNative(Native Method)
05-23 23:35:08.831: E/AndroidRuntime(30761):    at java.lang.reflect.Method.invoke(Method.java:511)
05-23 23:35:08.831: E/AndroidRuntime(30761):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
05-23 23:35:08.831: E/AndroidRuntime(30761):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
05-23 23:35:08.831: E/AndroidRuntime(30761):    at dalvik.system.NativeStart.main(Native Method)
05-23 23:35:08.831: E/AndroidRuntime(30761): Caused by: java.lang.StringIndexOutOfBoundsException: length=0; regionStart=0; regionLength=-2
05-23 23:35:08.831: E/AndroidRuntime(30761):    at java.lang.String.startEndAndLength(String.java:583)
05-23 23:35:08.831: E/AndroidRuntime(30761):    at java.lang.String.substring(String.java:1464)
05-23 23:35:08.831: E/AndroidRuntime(30761):    at com.HuskySoft.metrobike.backend.Utility.secondsToHumanReadableDuration(Utility.java:433)
05-23 23:35:08.831: E/AndroidRuntime(30761):    at com.HuskySoft.metrobike.ui.ResultsActivity.drawRoute(ResultsActivity.java:319)
05-23 23:35:08.831: E/AndroidRuntime(30761):    at com.HuskySoft.metrobike.ui.ResultsActivity.onResume(ResultsActivity.java:418)
05-23 23:35:08.831: E/AndroidRuntime(30761):    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1185)
05-23 23:35:08.831: E/AndroidRuntime(30761):    at android.app.Activity.performResume(Activity.java:5182)
05-23 23:35:08.831: E/AndroidRuntime(30761):    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2732)
05-23 23:35:08.831: E/AndroidRuntime(30761):    ... 12 more

It seems like a substring index issue, and may be hard to reproduce (since this problem is related to location).
Please fix it.

**Comment by CoolCapri** [comment]
@csmengwan @alaurenz
