### ISSUE TITLE
Crash trying to inflate settings for MainActivity

### ISSUE THREAD

**Issue by dutchscout** [alaurenz/metrobike#50]
Getting a crash trying to run the app.  It complains about not being able to find an onClick handler while inflating.  There is a chance that someone has simply forgotten to check in a recent edit to this file (?).

FATAL EXCEPTION: main
android.view.InflateException: Couldn't resolve menu item onClick handler goToSettingsPage in class android.view.ContextThemeWrapper
    at android.view.MenuInflater$InflatedOnMenuItemClickListener.<init>(MenuInflater.java:202)
    at android.view.MenuInflater$MenuState.setItem(MenuInflater.java:402)
    at android.view.MenuInflater$MenuState.addItem(MenuInflater.java:436)
    at android.view.MenuInflater.parseMenu(MenuInflater.java:173)
    at android.view.MenuInflater.inflate(MenuInflater.java:95)
    at com.HuskySoft.metrobike.ui.MainActivity.onCreateOptionsMenu(MainActivity.java:42)
    at android.app.Activity.onCreatePanelMenu(Activity.java:2444)
    at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:388)
    at com.android.internal.policy.impl.PhoneWindow.invalidatePanelMenu(PhoneWindow.java:739)
    at com.android.internal.policy.impl.PhoneWindow$1.run(PhoneWindow.java:2833)
    at android.os.Handler.handleCallback(Handler.java:605)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4424)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NoSuchMethodException: goToSettingsPage [interface android.view.MenuItem]
    at java.lang.Class.getConstructorOrMethod(Class.java:460)
    at java.lang.Class.getMethod(Class.java:915)
    at android.view.MenuInflater$InflatedOnMenuItemClickListener.<init>(MenuInflater.java:200)
    ... 18 more

**Comment by CoolCapri** [comment]
I pull the lates snapshot from GitHub and it works. Will you try to pull and then clean the project?

**Comment by csmengwan** [comment]
The current crashing reason is NULLPOINTER exception in Simple Algorithm

**Comment by sw11** [comment]
I think it should work for showing the settings in MainActivity.
The Nullpointer exception is in searchActivity

**Comment by CoolCapri** [comment]
Yes, and null pointer exception happened in DirectionRequest.doRequest(). The bug propagates to searchActivity and find button crashes. I cannot help with this right now because I am not working on algorithm or backend. See another issue I just created for details.

**Comment by sw11** [comment]
I find the FATAL EXCEPTION when I open on a tablet. 
Not sure why but I will work on that

**Comment by dutchscout** [comment]
Sorry about the Null Pointer issue in the backend... that is a separate issue.  We accidentally switched from the dummy JSON to live JSON before the live code was ready.  I'll be pushing a fix for that soon!

**Comment by sw11** [comment]
I am able to locate the the fatal exception.
I should about to fix it and push with in two hour.
NOTE: Try to test on different devices (different screen size)
As some of them may not work on a large screen devices.
Right now, I am testing on a 4 inch and 9.7 inch device.

**Comment by CoolCapri** [comment]
@sw11 Just try the latest snapshot. Does it work well now?

**Comment by dutchscout** [comment]
Current version still crashes on my tablet:

FATAL EXCEPTION: main
android.view.InflateException: Couldn't resolve menu item onClick handler goToSettingsPage in class android.view.ContextThemeWrapper
    at android.view.MenuInflater$InflatedOnMenuItemClickListener.<init>(MenuInflater.java:202)
    at android.view.MenuInflater$MenuState.setItem(MenuInflater.java:402)
    at android.view.MenuInflater$MenuState.addItem(MenuInflater.java:436)
    at android.view.MenuInflater.parseMenu(MenuInflater.java:173)
    at android.view.MenuInflater.inflate(MenuInflater.java:95)
    at com.HuskySoft.metrobike.ui.MainActivity.onCreateOptionsMenu(MainActivity.java:42)
    at android.app.Activity.onCreatePanelMenu(Activity.java:2444)
    at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:388)
    at com.android.internal.policy.impl.PhoneWindow.invalidatePanelMenu(PhoneWindow.java:739)
    at com.android.internal.policy.impl.PhoneWindow$1.run(PhoneWindow.java:2833)
    at android.os.Handler.handleCallback(Handler.java:605)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4424)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NoSuchMethodException: goToSettingsPage [interface android.view.MenuItem]
    at java.lang.Class.getConstructorOrMethod(Class.java:460)
    at java.lang.Class.getMethod(Class.java:915)
    at android.view.MenuInflater$InflatedOnMenuItemClickListener.<init>(MenuInflater.java:200)
    ... 18 more

**Comment by dutchscout** [comment]
My testing device is a Motorola Xoom (10.1 inch screen)

**Comment by sw11** [comment]
It should be fix now. 
Please pull the newest and test it

**Comment by dutchscout** [comment]
Yay!  It works - awesome :)
Thanks!
