### ISSUE TITLE
runtime exception when relaunch the app

### ISSUE THREAD

**Issue by sw11** [alaurenz/metrobike#63]
@alaurenz @meganca @CoolCapri @coreyh3 @smile76054789 
I open the app in the device, and then launch the app by clicking run button in eclipse, it gives me this error:

FATAL EXCEPTION: main

ava.lang.RuntimeException: Unable to instantiate application android.app.Application: java.lang.NullPointerException
at android.app.LoadedApk.makeApplication(LoadedApk.java:482)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3950)
at android.app.ActivityThread.access$1300(ActivityThread.java:127)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1197)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4507)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:978)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
android.app.LoadedApk.initializeJavaContextClassLoader(LoadedApk.java:362)
at android.app.LoadedApk.getClassLoader(LoadedApk.java:305)
at android.app.LoadedApk.makeApplication(LoadedApk.java:474)
... 11 more

It didn't crash, instead it will just run the app. Everything seems fine but I can see this error in the log.

**Comment by CoolCapri** [comment]
Check this link and you can find the answer http://stackoverflow.com/questions/10150899/runtimeexception-unable-to-instantiate-application

**Comment by sw11** [comment]
Thanks, I can see that. 
But do we need to address this issue in our bug system?
So we can tell the staff that it is not "actually" a bug?

**Comment by dutchscout** [comment]
It looks like this error my be coming from when the app is killed and before the new version is loaded.  Since this doesn't happen when a person is simply using the app, it shouldn't be a problem.  In fact, the TAs may not even see the message at all...

Now, we do need to be sure that our app doesn't crash if it gets minimized/restored/etc.  How well are we using onPause/onResume and onStop/onStart ?

**Comment by dutchscout** [comment]
We'll leave this issue open until after the TA grades our stuff, so they know that we know about it.

**Comment by dutchscout** [comment]
Closing this now...  Please reopen if this issue resurfaces.
